In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.random.random((4, 4))

array([[0.11416895, 0.62793676, 0.39184199, 0.49663591],
       [0.0159896 , 0.24410317, 0.92637358, 0.50395415],
       [0.83647103, 0.50956053, 0.89456878, 0.35407746],
       [0.27717243, 0.81389284, 0.97232256, 0.32360365]])

In [5]:
np.random.randint(50, 99, (10, 10))

array([[96, 73, 56, 70, 74, 84, 52, 98, 70, 66],
       [80, 56, 83, 54, 73, 87, 88, 88, 57, 60],
       [58, 59, 70, 84, 50, 64, 60, 89, 83, 74],
       [57, 88, 62, 75, 53, 53, 70, 62, 78, 95],
       [87, 83, 51, 65, 75, 73, 95, 97, 82, 80],
       [54, 65, 97, 90, 57, 56, 58, 86, 92, 71],
       [57, 97, 92, 58, 96, 80, 71, 81, 54, 95],
       [73, 54, 61, 55, 62, 81, 66, 95, 56, 67],
       [66, 96, 72, 86, 57, 88, 84, 77, 98, 96],
       [85, 63, 51, 61, 89, 70, 65, 74, 80, 92]])

In [14]:
np.ones((7, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
2 + 2

In [ ]:
5 ** 5

In [ ]:
6+1